node('master') {
   
   stage('initial')
   {
        git changelog: false, url: 'https://github.com/savishy/spring-petclinic.git';
       
   }
   stage('Build') {
       sh './mvnw install'
      }
      stage('ARCHIEVE') {
      
      archiveArtifacts '**/*.war'
   }
}